"""add dynamic vars to table

Revision ID: 4769b7a2546c
Revises: 8a5beebca8f3
Create Date: 2024-06-25 20:50:32.007035

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4769b7a2546c"
down_revision = "8a5beebca8f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("call", sa.Column("dynamic_vars", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("call", "dynamic_vars")
    # ### end Alembic commands ###
