"""create_call_model

Revision ID: 27cb7d9d1141
Revises: c79b0938ea4b
Create Date: 2024-06-03 19:49:32.936006

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "27cb7d9d1141"
down_revision = "c79b0938ea4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("link_to_recording", sa.String(length=512), nullable=True),
        sa.Column("call_title", sa.String(length=256), nullable=True),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user_account.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call")
    # ### end Alembic commands ###
