"""add script table and modify call table

Revision ID: 1b006494a7f8
Revises: ce4e05f11564
Create Date: 2024-06-04 16:49:55.661935

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1b006494a7f8"
down_revision = "ce4e05f11564"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "script",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("agent_id", sa.String(length=64), nullable=False),
        sa.Column("image", sa.String(length=512), nullable=True),
        sa.Column("sample_audio", sa.String(length=256), nullable=True),
        sa.Column("cost", sa.Integer(), nullable=False),
        sa.Column("fields", sa.JSON(), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("call", sa.Column("script_id", sa.BigInteger(), nullable=True))
    op.create_foreign_key(
        None, "call", "script", ["script_id"], ["id"], ondelete="SET NULL"
    )
    op.drop_column("call", "script_title")
    op.drop_column("call", "script_image")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "call",
        sa.Column(
            "script_image", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "call",
        sa.Column(
            "script_title", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "call", type_="foreignkey")
    op.drop_column("call", "script_id")
    op.drop_table("script")
    # ### end Alembic commands ###
