"""add ref code to user table

Revision ID: a20554aa4aae
Revises: c6e5229eafe7
Create Date: 2024-08-08 16:11:59.672025

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a20554aa4aae"
down_revision = "c6e5229eafe7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account", sa.Column("ref_code", sa.String(length=128), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "ref_code")
    # ### end Alembic commands ###
