"""add_fields_to_call_model

Revision ID: c5b487d96bdc
Revises: 27cb7d9d1141
Create Date: 2024-06-03 20:01:18.385337

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "c5b487d96bdc"
down_revision = "27cb7d9d1141"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "call", sa.Column("script_title", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "call", sa.Column("script_image", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "call", sa.Column("from_number", sa.String(length=256), nullable=True)
    )
    op.add_column("call", sa.Column("to_number", sa.String(length=256), nullable=True))
    op.drop_column("call", "call_title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "call",
        sa.Column(
            "call_title", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("call", "to_number")
    op.drop_column("call", "from_number")
    op.drop_column("call", "script_image")
    op.drop_column("call", "script_title")
    # ### end Alembic commands ###
