"""index sid

Revision ID: c6e5229eafe7
Revises: 7605f3ec9394
Create Date: 2024-06-26 14:27:28.352952

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c6e5229eafe7"
down_revision = "7605f3ec9394"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_call_twilio_call_sid"), "call", ["twilio_call_sid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_call_twilio_call_sid"), table_name="call")
    # ### end Alembic commands ###
