"""add sid to calls table

Revision ID: 8a5beebca8f3
Revises: 1b006494a7f8
Create Date: 2024-06-24 19:34:35.325339

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8a5beebca8f3"
down_revision = "1b006494a7f8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "call", sa.Column("twilio_call_sid", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("call", "twilio_call_sid")
    # ### end Alembic commands ###
