"""add intiated to status enum

Revision ID: fdcf4a21ec52
Revises: 7605f3ec9394
Create Date: 2024-06-26 12:31:36.111197

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "fdcf4a21ec52"
down_revision = "7605f3ec9394"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TYPE callstatus ADD VALUE IF NOT EXISTS 'initiated'")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
